0->25
apa:apa
baka:kaka
trodde:snodde
äta:räka
trycka:smycke
eskalera:minimera
omtyckt:otakt
mamma:amalgam
mustage:stelbent
människoätare:koskötare
arbetsmarknadsutbildning:marknadsföring
tillsättningsförfarande:behovstillfredsställelse